repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v0.8.3
    hooks:
      - id: go-fmt
      - id: go-lint
      - id: golangci-lint
